# Generated by Django 5.0.6 on 2024-05-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, choices=[('USA', 'Estados Unidos da América'), ('BRA', 'Brasil'), ('DEU', 'Alemanha'), ('GBR', 'Inglaterra'), ('CAN', 'Canáda'), ('FRA', 'França'), ('PRT', 'Portugal'), ('ESP', 'Espanha'), ('ARG', 'Argentina'), ('ITA', 'Itália'), ('URY', 'Uruguai'), ('MEX', 'México')], max_length=200, null=True)),
            ],
        ),
    ]
