# Generated by Django 5.0.6 on 2024-05-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ator',
            name='nacionalidade',
            field=models.CharField(blank=True, choices=[('USA', 'Estados Unidos da América'), ('BRA', 'Brasil'), ('DEU', 'Alemanha'), ('GBR', 'Inglaterra'), ('CAN', 'Canáda'), ('FRA', 'França'), ('PRT', 'Portugal'), ('ESP', 'Espanha'), ('ARG', 'Argentina'), ('ITA', 'Itália'), ('URY', 'Uruguai'), ('MEX', 'México'), ('OTHER', 'Outros')], max_length=200, null=True),
        ),
    ]
