# Generated by Django 5.0.6 on 2024-06-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_filme_review_review_filme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='filme',
            new_name='filmes',
        ),
    ]
