# Generated by Django 5.0.6 on 2024-06-03 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_filme_review_filmes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='filmes',
            new_name='filme',
        ),
    ]
