# Generated by Django 5.0.6 on 2024-06-03 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atores', '0002_alter_ator_nacionalidade'),
        ('generos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('data_lancamento', models.DateField(blank=True, null=True)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('atores', models.ManyToManyField(related_name='ator_filme', to='atores.ator')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genero_filme', to='generos.genero')),
            ],
        ),
    ]
